In [1]:
# DSCI Lab 4
# K181161 
# Muhammad Sufyan Siddiqui

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [11]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pd.read_csv("iris.data", names=names)
dataset


sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [12]:
dataset.shape

(150, 5)

In [13]:
dataset.groupby('class').size()

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [20]:
# train / test dataset
array = dataset.values
X = array[:,0:4]
Y = array[:,4]
t_size = 0.30
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size,
random_state=seed)
#print("X-Train= ",X_train)
#print("X-Test= ",X_test)
#print("Y-Train= ",Y_train)
# print("Y-Test= ",Y_test)

X-Train=  [[5.0 3.3 1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [6.0 2.2 4.0 1.0]
 [6.4 2.7 5.3 1.9]
 [4.7 3.2 1.6 0.2]
 [4.6 3.1 1.5 0.2]
 [5.1 3.4 1.5 0.2]
 [7.7 3.8 6.7 2.2]
 [4.3 3.0 1.1 0.1]
 [6.3 3.3 6.0 2.5]
 [5.5 2.4 3.7 1.0]
 [5.0 2.0 3.5 1.0]
 [6.5 2.8 4.6 1.5]
 [5.0 3.4 1.6 0.4]
 [4.4 2.9 1.4 0.2]
 [5.0 3.5 1.6 0.6]
 [6.7 3.1 4.7 1.5]
 [7.3 2.9 6.3 1.8]
 [5.5 2.6 4.4 1.2]
 [5.2 2.7 3.9 1.4]
 [5.7 4.4 1.5 0.4]
 [7.2 3.2 6.0 1.8]
 [5.4 3.4 1.7 0.2]
 [5.8 4.0 1.2 0.2]
 [6.1 2.6 5.6 1.4]
 [5.7 2.5 5.0 2.0]
 [4.8 3.0 1.4 0.1]
 [6.5 3.0 5.8 2.2]
 [4.6 3.2 1.4 0.2]
 [6.6 2.9 4.6 1.3]
 [6.7 3.0 5.2 2.3]
 [6.1 3.0 4.6 1.4]
 [5.7 3.8 1.7 0.3]
 [7.0 3.2 4.7 1.4]
 [4.7 3.2 1.3 0.2]
 [6.5 3.0 5.2 2.0]
 [7.7 2.6 6.9 2.3]
 [4.9 2.4 3.3 1.0]
 [4.8 3.1 1.6 0.2]
 [5.5 4.2 1.4 0.2]
 [5.6 3.0 4.1 1.3]
 [6.4 3.2 5.3 2.3]
 [5.2 3.5 1.5 0.2]
 [7.9 3.8 6.4 2.0]
 [5.8 2.8 5.1 2.4]
 [5.7 2.9 4.2 1.3]
 [5.1 3.7 1.5 0.4]
 [5.1 2.5 3.0 1.1]
 [5.0 3.4 1.5 0.2]
 [7.7 2.8 6.7 2.0]
 [7.6 3.0 6.6 2.1]
 [5.0 3.2 1.2 0.2]
 [

In [21]:
# Make predictions
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_test)
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

0.911111111111
[[12  0  0]
 [ 0 15  1]
 [ 0  3 14]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       0.83      0.94      0.88        16
 Iris-virginica       0.93      0.82      0.87        17

    avg / total       0.92      0.91      0.91        45



In [23]:
for k in range(1,11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, Y_train)
    predictions = knn.predict(X_test)
    print(" K=",k,"  Accuracy= ",accuracy_score(Y_test, predictions))


K= 1   Accuracy=  0.933333333333
 K= 2   Accuracy=  0.955555555556
 K= 3   Accuracy=  0.933333333333
 K= 4   Accuracy=  0.911111111111
 K= 5   Accuracy=  0.911111111111
 K= 6   Accuracy=  0.911111111111
 K= 7   Accuracy=  0.933333333333
 K= 8   Accuracy=  0.911111111111
 K= 9   Accuracy=  0.911111111111
 K= 10   Accuracy=  0.955555555556


In [24]:
for s in range(1,11):
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size,
    random_state=s)
    knn = KNeighborsClassifier()
    knn.fit(X_train, Y_train)
    predictions = knn.predict(X_test)
    print(" Seed=",s,"  Accuracy= ",accuracy_score(Y_test, predictions))


Seed= 1   Accuracy=  0.977777777778
 Seed= 2   Accuracy=  1.0
 Seed= 3   Accuracy=  0.955555555556
 Seed= 4   Accuracy=  0.977777777778
 Seed= 5   Accuracy=  0.955555555556
 Seed= 6   Accuracy=  0.977777777778
 Seed= 7   Accuracy=  0.911111111111
 Seed= 8   Accuracy=  0.955555555556
 Seed= 9   Accuracy=  1.0
 Seed= 10   Accuracy=  0.977777777778


In [1]:
#Q2
import pandas
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
names = ['date', 'temperature', 'humidity', 'light', 'CO2','humidity ratio','occupancy']
training_dataset = pandas.read_csv("datatraining.txt", names=names,skiprows=1)
testing_dataset1 = pandas.read_csv("datatest.txt", names=names,skiprows=1)
testing_dataset2 = pandas.read_csv("datatest2.txt", names=names,skiprows=1)
training_dataset.drop('date',axis='columns', inplace=True)
testing_dataset1.drop('date',axis='columns', inplace=True)
testing_dataset2.drop('date',axis='columns', inplace=True)
training_dataset.head()

temperature  humidity  light     CO2  humidity ratio  occupancy
1        23.18   27.2720  426.0  721.25        0.004793          1
2        23.15   27.2675  429.5  714.00        0.004783          1
3        23.15   27.2450  426.0  713.50        0.004779          1
4        23.15   27.2000  426.0  708.25        0.004772          1
5        23.10   27.2000  426.0  704.50        0.004757          1

In [2]:
training_dataset.shape

(8143, 6)

In [3]:
training_dataset.groupby('occupancy').size()

occupancy
0    6414
1    1729
dtype: int64

In [4]:
training_datasetv = training_dataset.values
testing_dataset1v = testing_dataset1.values
X_train = training_datasetv[:,0:5]
Y_train = training_datasetv[:,5]
X_test = testing_dataset1v[:,0:5]
Y_test = testing_dataset1v[:,5]

In [59]:
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_test)
#print(predictions)
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

[1. 1. 1. ... 1. 1. 1.]
0.9425891181988743
[[1645   48]
 [ 105  867]]
              precision    recall  f1-score   support

         0.0       0.94      0.97      0.96      1693
         1.0       0.95      0.89      0.92       972

    accuracy                           0.94      2665
   macro avg       0.94      0.93      0.94      2665
weighted avg       0.94      0.94      0.94      2665



In [6]:
for i in range(1,10):
    knn = KNeighborsClassifier(n_neighbors=i) 
    knn.fit(X_train, Y_train) 
    predictions = knn.predict(X_test) 
    print("K = ",i," ",accuracy_score(Y_test, predictions))

K =  1   0.9365853658536586
K =  2   0.9230769230769231
K =  3   0.9350844277673546
K =  4   0.9275797373358349
K =  5   0.9425891181988743
K =  6   0.9324577861163227
K =  7   0.9609756097560975
K =  8   0.9549718574108818
K =  9   0.9617260787992495


In [14]:
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [35]:
#Q3
import numpy as np

In [65]:
def ChiSq(row1,row2):
    dist=0.0
    for i in range(len(row1)-1):
        dist+=(row1[i]-row2[i])**2/(row1[i]+row2[i])
    return dist
def Neighbor(train_data, test_row):
    distances = list()
    for i in train_data:
        dist=ChiSq(test_row,i)
        distances.append((i[-1],dist))
    print("For the given test data:")
    print(test_row[:-1])
    print("Predicted class is:")
    print("1NN: ",min(distances))

def InitiatorSelf1NN(dataset):
    dataset.reset_index(drop=True,inplace=True)
    train_data=list(list(dataset.values))
    test_row=train_data[0]
    test_row=list(test_row)
    train_data.pop(0)
    Neighbor(train_data,test_row)
InitiatorSelf1NN(dataset)
InitiatorSelf1NN(training_dataset)


For the given test data:
[5.1, 3.5, 1.4, 0.2]
Predicted class is:
1NN:  ('Iris-setosa', 0.0023985497141263377)
For the given test data:
[23.18, 27.272, 426.0, 721.25, 0.0047929881765052]
Predicted class is:
1NN:  (0.0, 2.57609335447451)
